services:
  minio:
    image: minio/minio:latest
    container_name: s3webapp-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
    ports:
      - "9070:9000"
      - "9072:9001"
    volumes:
      - ./data/minio:/data

  backend:
    build: .
    container_name: s3webapp-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9080:9080"
    depends_on:
      - minio
