server:
  port: 9080

app:
  cors:
    allowed-origins:
      - http://localhost:9071
      - http://localhost:9080

s3:
  buckets:
    - id: logs
      name: "Local Minio - Logs"
      bucketName: "logs"
      endpointUrl: "http://minio:9000"
      accessKey: "minioadmin"
      secretKey: "minioadmin"
      region: "us-east-1"
      pathStyleAccess: true
    - id: backups
      name: "Local Minio - Backups"
      bucketName: "backups"
      endpointUrl: "http://minio:9000"
      accessKey: "minioadmin"
      secretKey: "minioadmin"
      region: "us-east-1"
      pathStyleAccess: true

security:
  ldap:
    url: "ldap://localhost:1389"
    base-dn: "dc=example,dc=com"
    bind-dn: "cn=ldap-reader,ou=ServiceAccounts,dc=example,dc=com"
    bind-password: "readerpass"
    user-search-base: "ou=Users,dc=example,dc=com"
    user-search-filter: "(sAMAccountName={0})"
    read-only-groups:
      - "cn=S3_ReadOnly,ou=Groups,dc=example,dc=com"
    read-write-groups:
      - "cn=S3_ReadWrite,ou=Groups,dc=example,dc=com"
    read-only-users: []
    read-write-users:
      - "carol"
    ignore-ssl-validation: true
    no-role-policy: DENY
    embedded:
      enabled: true
      port: 1389
      base-dn: "dc=example,dc=com"
      seed-ldif: "classpath:ldap/seed.ldif"
